file = io.open("test_read_lines.DATA", "r")
print(file:read("*all"))
print(file:read("*line"))
io.close()
file = io.open("test_read_lines.DATA", "r")
print(file:read("*line"))
print("That was one line.")
print(file:read("*all"))
io.close()
